// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: battle.proto

#pragma warning disable 1591, 0612, 3021

namespace easy_moba
{

    [global::ProtoBuf.ProtoContract()]
    public partial class req_battle_action
    {
        public req_battle_action()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint svr_ts { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint client_seq { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public t_lang user_id { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint action_flag { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_battle_action
    {
        public reply_battle_action()
        {
            err_code = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint svr_ts { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint client_seq { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public t_lang user_id { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string err_code { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint svr_seq { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint action_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class req_battle_move
    {
        public req_battle_move()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint svr_ts { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint client_seq { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public t_lang user_id { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public float move_rotation_X { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public float move_rotation_y { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_battle_move
    {
        public reply_battle_move()
        {
            err_code = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint svr_ts { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint client_seq { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public t_lang user_id { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string err_code { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint svr_seq { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public float move_rotation_X { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public float move_rotation_y { get; set; }

    }

}

#pragma warning restore 1591, 0612, 3021
