// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: down.proto

#pragma warning disable 1591, 0612, 3021

namespace easy_moba
{

    [global::ProtoBuf.ProtoContract()]
    public partial class down_msg
    {
        public down_msg()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint svr_ts { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint seq { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public reply_err_code err_code { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public reply_notify notify { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public reply_extra_info extra_info { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public reply_heartbeat heartbeat { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public reply_user gm { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public reply_sdk_login sdk_login { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public reply_login login { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public reply_reconnect reconnect { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public reply_tutorial tutorial { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public reply_settings settings { get; set; }

        [global::ProtoBuf.ProtoMember(99)]
        public reply_data_op data_op { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_user
    {
        public reply_user()
        {
            name = "";
            red_dots = new global::System.Collections.Generic.List<red_dot>();
            settings = new global::System.Collections.Generic.List<setting>();
            avatar = "";
            desc = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint level { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint exp { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<red_dot> red_dots { get; private set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<setting> settings { get; private set; }

        [global::ProtoBuf.ProtoMember(7, IsPacked = true)]
        public uint[] tutorials { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public t_lang lang { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int time_zone { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public uint frame { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public t_gender gender { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public uint country { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public uint city { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        [global::System.ComponentModel.DefaultValue("")]
        public string desc { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_msg
    {
        public reply_msg()
        {
            OnConstructor();
        }

        partial void OnConstructor();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_err_code
    {
        public reply_err_code()
        {
            err_code = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string err_code { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_notify
    {
        public reply_notify()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public red_dot red_dot { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_extra_info
    {
        public reply_extra_info()
        {
            OnConstructor();
        }

        partial void OnConstructor();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_heartbeat
    {
        public reply_heartbeat()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint delay { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_sdk_login
    {
        public reply_sdk_login()
        {
            token = "";
            host = "";
            open_id = "";
            union_id = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string token { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint svr_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string host { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string open_id { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string union_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_login
    {
        public reply_login()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public reply_user user { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint svr_time_zone { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public t_region region { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_reconnect
    {
        public reply_reconnect()
        {
            notifies = new global::System.Collections.Generic.List<reply_notify>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<reply_notify> notifies { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_tutorial
    {
        public reply_tutorial()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public reply_new_tutorial new_tutorial { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_new_tutorial
    {
        public reply_new_tutorial()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public t_result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint tutorials { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_settings
    {
        public reply_settings()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public t_result result { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class reply_data_op
    {
        public reply_data_op()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public t_result result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum t_result
    {
        success = 0,
        fail = 1,
    }

}

#pragma warning restore 1591, 0612, 3021
