// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: up.proto

#pragma warning disable 1591, 0612, 3021

namespace easy_moba
{

    [global::ProtoBuf.ProtoContract()]
    public partial class req_msg
    {
        public req_msg()
        {
            OnConstructor();
        }

        partial void OnConstructor();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class up_msg
    {
        public up_msg()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint seq { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint repeat { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public req_heartbeat heartbeat { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public req_gm gm { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public req_sdk_login sdk_login { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public req_login login { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public req_reconnect reconnect { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public req_tutorial tutorial { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public req_settings settings { get; set; }

        [global::ProtoBuf.ProtoMember(99)]
        public req_data_op data_op { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class req_heartbeat
    {
        public req_heartbeat()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class req_gm
    {
        public req_gm()
        {
            OnConstructor();
        }

        partial void OnConstructor();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class req_sdk_login
    {
        public req_sdk_login()
        {
            open_id = "";
            token = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public t_platform platform { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string open_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string token { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint svr_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class req_login
    {
        public req_login()
        {
            open_id = "";
            token = "";
            cli_version = "";
            jpush_id = "";
            idfa = "";
            google_aid = "";
            android_id = "";
            os_version = "";
            app_version = "";
            device = "";
            channel_id = "";
            package = "";
            avatar = "";
            union_id = "";
            name = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public t_platform platform { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public t_os os { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string open_id { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint svr_id { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string token { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public t_lang lang { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string cli_version { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int time_zone { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string jpush_id { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string idfa { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string google_aid { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue("")]
        public string android_id { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue("")]
        public string os_version { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.ComponentModel.DefaultValue("")]
        public string app_version { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        [global::System.ComponentModel.DefaultValue("")]
        public string device { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        [global::System.ComponentModel.DefaultValue("")]
        public string channel_id { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue("")]
        public string package { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        [global::System.ComponentModel.DefaultValue("")]
        public string union_id { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class req_reconnect
    {
        public req_reconnect()
        {
            token = "";
            cli_version = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint uid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string token { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string cli_version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class req_tutorial
    {
        public req_tutorial()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1, IsPacked = true)]
        public uint[] new_tutorials { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class req_settings
    {
        public req_settings()
        {
            settings = new global::System.Collections.Generic.List<setting>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<setting> settings { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class req_data_op
    {
        public req_data_op()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public t_op op { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint data { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public uint[] data_list { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum t_op
    {
        add = 0,
        sub = 1,
        mul = 2,
        div = 3,
    }

}

#pragma warning restore 1591, 0612, 3021
