%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.2.1

-ifndef(battle_pb).
-define(battle_pb, true).

-define(battle_pb_gpb_version, "4.2.1").

-ifndef('REQ_BATTLE_ACTION_PB_H').
-define('REQ_BATTLE_ACTION_PB_H', true).
-record(req_battle_action,
        {svr_ts = 0             :: non_neg_integer() | undefined, % = 1, 32 bits
         client_seq = 0         :: non_neg_integer() | undefined, % = 2, 32 bits
         user_id = cn           :: 'cn' | 'en' | integer() | undefined, % = 3, enum t_lang
         action_flag = 0        :: non_neg_integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('REPLY_BATTLE_ACTION_PB_H').
-define('REPLY_BATTLE_ACTION_PB_H', true).
-record(reply_battle_action,
        {svr_ts = 0             :: non_neg_integer() | undefined, % = 1, 32 bits
         client_seq = 0         :: non_neg_integer() | undefined, % = 2, 32 bits
         user_id = cn           :: 'cn' | 'en' | integer() | undefined, % = 3, enum t_lang
         err_code = []          :: iolist() | undefined, % = 4
         svr_seq = 0            :: non_neg_integer() | undefined, % = 5, 32 bits
         action_id = 0          :: non_neg_integer() | undefined % = 6, 32 bits
        }).
-endif.

-ifndef('REQ_BATTLE_MOVE_PB_H').
-define('REQ_BATTLE_MOVE_PB_H', true).
-record(req_battle_move,
        {svr_ts = 0             :: non_neg_integer() | undefined, % = 1, 32 bits
         client_seq = 0         :: non_neg_integer() | undefined, % = 2, 32 bits
         user_id = cn           :: 'cn' | 'en' | integer() | undefined, % = 3, enum t_lang
         move_rotation_X = 0.0  :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
         move_rotation_y = 0.0  :: float() | integer() | infinity | '-infinity' | nan | undefined % = 5
        }).
-endif.

-ifndef('REPLY_BATTLE_MOVE_PB_H').
-define('REPLY_BATTLE_MOVE_PB_H', true).
-record(reply_battle_move,
        {svr_ts = 0             :: non_neg_integer() | undefined, % = 1, 32 bits
         client_seq = 0         :: non_neg_integer() | undefined, % = 2, 32 bits
         user_id = cn           :: 'cn' | 'en' | integer() | undefined, % = 3, enum t_lang
         err_code = []          :: iolist() | undefined, % = 4
         svr_seq = 0            :: non_neg_integer() | undefined, % = 5, 32 bits
         move_rotation_X = 0.0  :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 6
         move_rotation_y = 0.0  :: float() | integer() | infinity | '-infinity' | nan | undefined % = 7
        }).
-endif.

-ifndef('RED_DOT_PB_H').
-define('RED_DOT_PB_H', true).
-record(red_dot,
        {type = none            :: 'none' | integer() | undefined, % = 1, enum t_red_dot
         id = 0                 :: non_neg_integer() | undefined, % = 2, 32 bits
         start_time = 0         :: non_neg_integer() | undefined, % = 3, 32 bits
         expire_time = 0        :: non_neg_integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('SETTING_PB_H').
-define('SETTING_PB_H', true).
-record(setting,
        {key = sound            :: 'sound' | 'music' | integer() | undefined, % = 1, enum t_setting
         value = 0              :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-endif.
