%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.2.1

-ifndef(bt_common_pb).
-define(bt_common_pb, true).

-define(bt_common_pb_gpb_version, "4.2.1").

-ifndef('BT_ACTION_PB_H').
-define('BT_ACTION_PB_H', true).
-record(bt_action,
        {type = nothing         :: 'nothing' | 'move' | 'hit' | 'eat' | 'back_home' | integer() | undefined, % = 1, enum t_bt_action
         op_slot = 0            :: non_neg_integer() | undefined, % = 2, 32 bits
         op_param = 0           :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('BT_CMD_PB_H').
-define('BT_CMD_PB_H', true).
-record(bt_cmd,
        {uid = 0                :: non_neg_integer() | undefined, % = 1, 32 bits
         client_seq = 0         :: non_neg_integer() | undefined, % = 2, 32 bits
         actions = []           :: [bt_common_pb:bt_action()] | undefined % = 3
        }).
-endif.

-ifndef('BT_SEQ_PB_H').
-define('BT_SEQ_PB_H', true).
-record(bt_seq,
        {seq = 0                :: non_neg_integer() | undefined, % = 1, 32 bits
         cmds = []              :: [bt_common_pb:bt_cmd()] | undefined % = 2
        }).
-endif.

-endif.
