%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.2.1

-ifndef(common_pb).
-define(common_pb, true).

-define(common_pb_gpb_version, "4.2.1").

-ifndef('RED_DOT_PB_H').
-define('RED_DOT_PB_H', true).
-record(red_dot,
        {type = none            :: 'none' | integer() | undefined, % = 1, enum t_red_dot
         id = 0                 :: non_neg_integer() | undefined, % = 2, 32 bits
         start_time = 0         :: non_neg_integer() | undefined, % = 3, 32 bits
         expire_time = 0        :: non_neg_integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('SETTING_PB_H').
-define('SETTING_PB_H', true).
-record(setting,
        {key = sound            :: 'sound' | 'music' | integer() | undefined, % = 1, enum t_setting
         value = 0              :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-endif.
