%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.2.1

-ifndef(up_pb).
-define(up_pb, true).

-define(up_pb_gpb_version, "4.2.1").

-ifndef('REQ_MSG_PB_H').
-define('REQ_MSG_PB_H', true).
-record(req_msg,
        {
        }).
-endif.

-ifndef('UP_MSG_PB_H').
-define('UP_MSG_PB_H', true).
-record(up_msg,
        {seq = 0                :: non_neg_integer() | undefined, % = 1, 32 bits
         repeat = 0             :: non_neg_integer() | undefined, % = 2, 32 bits
         heartbeat = undefined  :: up_pb:req_heartbeat() | undefined, % = 3
         gm = undefined         :: up_pb:req_gm() | undefined, % = 4
         sdk_login = undefined  :: up_pb:req_sdk_login() | undefined, % = 5
         login = undefined      :: up_pb:req_login() | undefined, % = 6
         reconnect = undefined  :: up_pb:req_reconnect() | undefined, % = 7
         tutorial = undefined   :: up_pb:req_tutorial() | undefined, % = 8
         settings = undefined   :: up_pb:req_settings() | undefined, % = 9
         data_op = undefined    :: up_pb:req_data_op() | undefined % = 99
        }).
-endif.

-ifndef('REQ_HEARTBEAT_PB_H').
-define('REQ_HEARTBEAT_PB_H', true).
-record(req_heartbeat,
        {time = 0               :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('REQ_GM_PB_H').
-define('REQ_GM_PB_H', true).
-record(req_gm,
        {
        }).
-endif.

-ifndef('REQ_SDK_LOGIN_PB_H').
-define('REQ_SDK_LOGIN_PB_H', true).
-record(req_sdk_login,
        {platform = default     :: 'default' | integer() | undefined, % = 1, enum t_platform
         open_id = []           :: iolist() | undefined, % = 2
         token = []             :: iolist() | undefined, % = 3
         svr_id = 0             :: non_neg_integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('REQ_LOGIN_PB_H').
-define('REQ_LOGIN_PB_H', true).
-record(req_login,
        {platform = default     :: 'default' | integer() | undefined, % = 1, enum t_platform
         os = ios               :: 'ios' | 'android' | 'web' | integer() | undefined, % = 2, enum t_os
         open_id = []           :: iolist() | undefined, % = 3
         svr_id = 0             :: non_neg_integer() | undefined, % = 4, 32 bits
         token = []             :: iolist() | undefined, % = 5
         lang = cn              :: 'cn' | 'en' | integer() | undefined, % = 6, enum t_lang
         cli_version = []       :: iolist() | undefined, % = 7
         time_zone = 0          :: integer() | undefined, % = 8, 32 bits
         jpush_id = []          :: iolist() | undefined, % = 9
         idfa = []              :: iolist() | undefined, % = 10
         google_aid = []        :: iolist() | undefined, % = 11
         android_id = []        :: iolist() | undefined, % = 12
         os_version = []        :: iolist() | undefined, % = 13
         app_version = []       :: iolist() | undefined, % = 14
         device = []            :: iolist() | undefined, % = 15
         channel_id = []        :: iolist() | undefined, % = 16
         package = []           :: iolist() | undefined, % = 17
         avatar = []            :: iolist() | undefined, % = 18
         union_id = []          :: iolist() | undefined, % = 19
         name = []              :: iolist() | undefined % = 20
        }).
-endif.

-ifndef('REQ_RECONNECT_PB_H').
-define('REQ_RECONNECT_PB_H', true).
-record(req_reconnect,
        {uid = 0                :: non_neg_integer() | undefined, % = 1, 32 bits
         token = []             :: iolist() | undefined, % = 2
         cli_version = []       :: iolist() | undefined % = 3
        }).
-endif.

-ifndef('REQ_TUTORIAL_PB_H').
-define('REQ_TUTORIAL_PB_H', true).
-record(req_tutorial,
        {new_tutorials = []     :: [non_neg_integer()] | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('REQ_SETTINGS_PB_H').
-define('REQ_SETTINGS_PB_H', true).
-record(req_settings,
        {settings = []          :: [up_pb:setting()] | undefined % = 1
        }).
-endif.

-ifndef('REQ_DATA_OP_PB_H').
-define('REQ_DATA_OP_PB_H', true).
-record(req_data_op,
        {op = add               :: 'add' | 'sub' | 'mul' | 'div' | integer() | undefined, % = 1, enum t_op
         data = 0               :: non_neg_integer() | undefined, % = 2, 32 bits
         data_list = []         :: [non_neg_integer()] | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('RED_DOT_PB_H').
-define('RED_DOT_PB_H', true).
-record(red_dot,
        {type = none            :: 'none' | integer() | undefined, % = 1, enum t_red_dot
         id = 0                 :: non_neg_integer() | undefined, % = 2, 32 bits
         start_ts = 0           :: non_neg_integer() | undefined, % = 3, 32 bits
         expire_ts = 0          :: non_neg_integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('SETTING_PB_H').
-define('SETTING_PB_H', true).
-record(setting,
        {key = sound            :: 'sound' | 'music' | integer() | undefined, % = 1, enum t_setting
         value = 0              :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-endif.
